name: Genera Metrics per il README

on:
  schedule:
    - cron: "0 23 * * *"  # Runs at 23:00 UTC, which is midnight Rome time (CET)
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg-agent \
            software-properties-common \
            jq
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository \
            "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) \
            stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - name: Verify Dependencies
        run: |
          for DEPENDENCY in docker jq; do
            if ! which $DEPENDENCY > /dev/null 2>&1; then
              echo "::error::\"$DEPENDENCY\" is not installed on current runner but is needed to run metrics"
              exit 1
            fi
          done

      - name: Genera il file metrics con lingue, statistiche e attività
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }} # Token di accesso
          base: header, repositories, metadata, activity
          config_timezone: Europe/Rome

          # Statistiche sui linguaggi
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_categories: programming
          plugin_languages_limit: 8

          # Attività recente
          plugin_activity: yes
          plugin_activity_limit: 5

          # Calendario delle attività su GitHub
          plugin_calendar: yes

          # Configurazioni facoltative
          custom_title: 'Statistiche del mio GitHub'
          custom_footer: 'Generated by lowlighter/metrics'
